services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim-faststart
    container_name: oracle-db
    environment:
      - ORACLE_PASSWORD=admin
    ports:
      - "1521:1521"
    healthcheck:
      test: [ "CMD", "healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce-network

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"
    networks:
      - ecommerce-network

  user-service:
    build: ./user-service
    container_name: user-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/FREEPDB1
      - SPRING_DATASOURCE_USERNAME=USER_SERVICE
      - SPRING_DATASOURCE_PASSWORD=user_password
    depends_on:
      oracle-db:
        condition: service_healthy
    networks:
      - ecommerce-network

  product-service:
    build: ./product-service
    container_name: product-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/FREEPDB1
      - SPRING_DATASOURCE_USERNAME=PRODUCT_SERVICE
      - SPRING_DATASOURCE_PASSWORD=product_password
    depends_on:
      oracle-db:
        condition: service_healthy
    networks:
      - ecommerce-network

  order-service:
    build: ./order-service
    container_name: order-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/FREEPDB1
      - SPRING_DATASOURCE_USERNAME=ORDER_SERVICE
      - SPRING_DATASOURCE_PASSWORD=order_password
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - PRODUCT_SERVICE_URL=http://product-service:8081
    depends_on:
      oracle-db:
        condition: service_healthy
      kafka:
        condition: service_started
      product-service:
        condition: service_started
    networks:
      - ecommerce-network

  payment-service:
    build: ./payment-service
    container_name: payment-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/FREEPDB1
      - SPRING_DATASOURCE_USERNAME=PAYMENT_SERVICE
      - SPRING_DATASOURCE_PASSWORD=payment_password
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      oracle-db:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - ecommerce-network

  notification-service:
    build: ./notification-service
    container_name: notification-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/FREEPDB1
      - SPRING_DATASOURCE_USERNAME=NOTIFICATION_SERVICE
      - SPRING_DATASOURCE_PASSWORD=notification_password
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      oracle-db:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - ecommerce-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "9000:9000"
    environment:
      - USER_SERVICE_URL=http://user-service:8081
      - PRODUCT_SERVICE_URL=http://product-service:8081
      - ORDER_SERVICE_URL=http://order-service:8082
      - PAYMENT_SERVICE_URL=http://payment-service:8083
      - NOTIFICATION_SERVICE_URL=http://notification-service:8084
    depends_on:
      user-service:
        condition: service_started
      product-service:
        condition: service_started
      order-service:
        condition: service_started
      payment-service:
        condition: service_started
      notification-service:
        condition: service_started
    networks:
      - ecommerce-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - ecommerce-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
